#pragma once

struct sprite;

enum resid : unsigned short {
	NONE,
	FONT6, FONT8, FONT10, FONT3, FONT16,
	MENTATS, MENSHPA, MENSHPH, MENSHPO, MENSHPM,
	SHAPES, ICONS, ARROWS, MOUSE, SCREEN, CHOAM,
	UNITS, UNITS1, UNITS2,
	SLAB4, AFINALA, AFINALB, BARRAC, CARRYALL,
	CONSTRUC, EFINALA, EFINALB, FARTR, FHARK,
	FORDOS, FREMEN, GOLDBB, HARKTANK, HARVEST,
	HEADQRTS, HFINALA, HFINALB, HFINALC, HITCFTRY,
	HTANK, HVYFTRY, HYINFY, INFANTRY, INTRO1,
	INTRO10, INTRO11, INTRO2, INTRO3, INTRO4,
	INTRO5, INTRO6, INTRO7A, INTRO7B, INTRO8A,
	INTRO8B, INTRO8C, INTRO9, IX, LITEFTRY,
	LOSTBILD, LOSTVEHC, LTANK, MCV, MEANWHIL,
	OFINALA, OFINALB, OFINALC, OFINALD, ORDRTANK,
	ORNI, OTRIKE, PALACE, QUAD, REFINERY,
	REPAIR, RTANK, RTURRET, SABOTURE, SARDUKAR,
	SLAB, STANK, STARPORT, STATIC, STORAGE,
	TRIKE, TURRET, WALL, WESTWOOD, WIN1,
	WIN2, WINDTRAP, WOR, WORM,
};
struct residi {
	const char*	id;
	const char*	folder;
	sprite*		data;
	int			size;
	bool		error;
	sprite*		get();
};
void clear_sprites();
void save_sprite(resid id);
const sprite* gres(resid i);
// const sprite* gres(const char* id);